#!/usr/bin/env python3
"""migrate_9router_journal.py (LOW-239): 9router_<date>.json -> English keys.

Guards: the script's maps equal the approved table; what monitor_9router writes today is
already the migrated shape (migrate() leaves it unchanged); dry-run writes nothing; real run
renames keys, backs up originals, journals, leaves the .md alone; the migrated files render
through the NEW write_md / still_for / summary_tele / journal_web list page / Ada gather to the
same bytes the OLD code (HEAD before LOW-239) rendered from the old files — goldens in
tests/golden/router_journal_low239/expected were generated by running that old code on
tests/golden/router_journal_low239/old; an unknown shape refuses the whole run; re-run is a
no-op. Also: display labels keyed by the new codes keep the old text (journal note kinds)."""
import json
import shutil
import sqlite3
import subprocess
import sys
import tarfile
import tempfile
from datetime import datetime as _datetime
from pathlib import Path
from unittest import mock

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "tests"))
import state_paths as sp                                      # noqa: E402

GOLDEN = ROOT / "tests" / "golden" / "router_journal_low239"
OLD_DIR, EXPECTED = GOLDEN / "old", GOLDEN / "expected"
TABLE = json.loads((ROOT / "docs" / "tu_dien_ten" / "journal_keys_v2.json").read_text(encoding="utf-8"))
WEB_URL = "http://100.87.121.46:9130"          # value the goldens were rendered with


def _clean(d):
    return {k: v for k, v in d.items() if not k.startswith("_")}


def _layout(tmp: Path, extra=None) -> dict:
    """Copy the old fixtures (+ their .md) into tmp/state/9router/journal/."""
    j = tmp / "state" / "9router" / sp.JOURNAL_DIR
    j.mkdir(parents=True)
    files = {}
    for p in sorted(OLD_DIR.glob("9router_*.json")):
        shutil.copy(p, j / p.name)
        files[p.stem] = j / p.name
    (j / "9router_2026-09-15.md").write_text("md is not touched\n", encoding="utf-8")
    files["md"] = j / "9router_2026-09-15.md"
    for name, data in (extra or {}).items():
        (j / name).write_text(json.dumps(data, ensure_ascii=False), encoding="utf-8")
        files[name] = j / name
    return files


def _run(tmp: Path, *extra):
    return subprocess.run([sys.executable, str(ROOT / "migrate_9router_journal.py"), "--state", str(tmp / "state"),
                           *extra], capture_output=True, text=True, cwd=ROOT)


def _bytes(files: dict) -> dict:
    return {k: p.read_bytes() for k, p in files.items()}


# ------------------------------------------------------------ table <-> code
def test_maps_equal_approved_table():
    import migrate_9router_journal as m
    t = m.tables()
    want = {k: _clean(v) for k, v in TABLE.items() if k.startswith("router_journal")}
    assert set(t) == set(want), (sorted(t), sorted(want))
    for k in want:
        assert t[k] == want[k], (k, t[k], want[k])


def test_journal_note_kind_labels_keep_old_text():
    """`kind` codes come from the table; the label printed on the .md page is the old text."""
    import journal
    kinds = _clean(TABLE["journal_notes.kind"])
    old_labels = {"bug": "🐞 Bug", "fix": "🔧 Đã sửa", "van-de": "⚠️ Vấn đề",
                  "ghi-chu": "📝 Ghi chú", "quyet-dinh": "🎯 Quyết định"}
    assert journal.TYPE == {kinds[old]: label for old, label in old_labels.items()}, journal.TYPE


def test_monitor_writes_already_migrated_shape():
    """Every key the current code writes is covered: migrate() is a no-op on its output."""
    import migrate_9router_journal as m
    import monitor_9router as tr
    from test_function_pure import _line
    rows = [_line(0, "a", ptok=5000, ctok=0), _line(10, "b", status="error 500")]
    with mock.patch.object(tr, "inspect_model", lambda tm, combo: (
            [{"model": "x", "req": 1, "prompt": 2, "usd": 0.1, "cache_pct": 0.0}],
            [{"model": "y", "prompt": 30000, "cache_pct": 1.0, "config_roles": ["engine anh:vision"]}])):
        so_lieu, tho = tr.aggregate(rows, cap_fb=set())
    con = sqlite3.connect(":memory:")
    con.execute("create table providerConnections (name, provider, isActive, data, updatedAt)")
    con.execute("insert into providerConnections values ('c', 'p', 1, ?, '')",
                (json.dumps({"testStatus": "unavailable", "errorCode": 429, "lastError": "x",
                             "lastErrorAt": "2026-09-05T18:00:00.000Z", "backoffLevel": 1}),))
    with tempfile.TemporaryDirectory() as t, \
            mock.patch.object(tr, "HERMES_HOMES", [Path(t) / ".hermes-blog"]), \
            mock.patch.object(tr, "DB", Path(t) / "none.sqlite"), \
            mock.patch.object(tr, "DRAFTS", Path(t)), \
            mock.patch.object(tr.hermes_adapter, "state_db_each_profile",
                              lambda home: [home / "profiles" / "miles" / "state.db",
                                            home / "profiles" / "qinn" / "state.db"]), \
            mock.patch.object(tr.hermes_adapter, "use_by_model", lambda p, e0, e1: None if "qinn" in str(p) else [
                {"model": "a", "api": 2, "in": 10, "out": 5, "cache": 1, "reasoning": 0, "sessions": 1}]), \
            mock.patch.object(tr.hermes_adapter, "count_done_by_role", lambda e0, e1, db=None: {"miles": 1}):
        (Path(t) / "d1.json").write_text(json.dumps({"status": "published", "brand": "donniechublog"}))
        role_costs = tr.gather_role("2026-09-06", tho["by_model"], tho["totals"])
    doc = {"date": "2026-09-06", "utc_window": ["a", "b"], **so_lieu,
           "connection_errors": tr.error_connection(con, "2026-09-05T17:00:00.000Z", "2026-09-06T17:00:00.000Z"),
           "role_costs": role_costs}
    assert doc["connection_errors"] and doc["role_costs"]["by_role"] and doc["role_costs"]["by_brand"], doc
    assert doc["role_costs"]["unreadable_profiles"] == ["blog/qinn"], doc["role_costs"]
    assert m.migrate(doc) == doc
    err = {"date": "2026-09-06", "read_error": "x"}
    assert m.migrate(err) == err
    assert set(doc) | set(err) == set(m.TOP_KEY_MAP.values()) - {"legacy_connection"} | set(m.TOP_FIXED)


# ------------------------------------------------------------ script
def test_dry_run_writes_nothing():
    with tempfile.TemporaryDirectory() as t:
        tmp = Path(t)
        f = _layout(tmp)
        before = _bytes(f)
        r = _run(tmp, "--dry-run")
        assert r.returncode == 0 and "DRY RUN — 3 file(s)" in r.stdout, (r.stdout, r.stderr)
        assert _bytes(f) == before and not list(tmp.glob("*.tar.gz")) and not list(tmp.glob("*.jsonl"))


def test_real_run_renders_same_bytes_as_old_code():
    import ada_prepare
    import journal_web
    import monitor_9router as tr
    with tempfile.TemporaryDirectory() as t:
        tmp = Path(t)
        f = _layout(tmp)
        before = _bytes(f)
        r = _run(tmp)
        assert r.returncode == 0, (r.stdout, r.stderr)
        assert f["md"].read_bytes() == before["md"], ".md must not be touched"
        (backup,) = tmp.glob("low239_9router_journal_backup_*.tar.gz")
        json_keys = sorted(k for k in f if k != "md")
        with tarfile.open(backup) as tar:
            assert sorted(tar.getnames()) == sorted(str(f[k].relative_to(tmp)) for k in json_keys)
            assert tar.extractfile(str(f["9router_2026-09-15"].relative_to(tmp))).read() == before["9router_2026-09-15"]
        (journal,) = tmp.glob("low239_9router_journal_*.journal.jsonl")
        rows = {x["file"]: x for x in (json.loads(y) for y in journal.read_text(encoding="utf-8").splitlines())}
        assert set(rows) == {str(f[k]) for k in json_keys}, rows
        assert rows[str(f["9router_2026-09-13"])]["to_keys"] == ["date", "read_error"]

        journal_dir = f["9router_2026-09-15"].parent
        with mock.patch.object(tr, "WEB_URL", WEB_URL), mock.patch.object(tr, "JOURNAL", journal_dir):
            for p in sorted(journal_dir.glob("9router_*.json")):
                m = json.loads(p.read_text(encoding="utf-8"))
                assert "ngay" not in m and "loi_doc" not in m, m
                d = m["date"]
                assert tr.write_md(m) == (EXPECTED / f"{d}.md").read_text(encoding="utf-8"), d
                assert tr.still_for(m) == json.loads((EXPECTED / f"{d}.still_for.json").read_text(encoding="utf-8")), d
                assert tr.summary_tele(m) == (EXPECTED / f"{d}.tele.txt").read_text(encoding="utf-8"), d
            assert journal_web.page_list_clean() == (EXPECTED / "list.html").read_bytes()

            # Ada reads the new keys, its own dump keeps the old keys (LOW-243)
            files = iter(sorted(journal_dir.glob("9router_*.json")))

            class _Fixed(_datetime):
                @classmethod
                def now(cls, tz=None):
                    return _datetime(2026, 9, 15, 8, 0, tzinfo=tz)
            with mock.patch.object(tr, "download", lambda d, lam_moi=False: json.loads(next(files).read_text(encoding="utf-8"))), \
                    mock.patch.object(ada_prepare, "datetime", _Fixed):
                got = ada_prepare.gather_9router(2)
            assert got == json.loads((EXPECTED / "ada_gather_9router.json").read_text(encoding="utf-8")), got


def test_bad_shape_or_conflict_refuses_everything():
    cases = (({"ngay": "d", "date": "d"}, "both"),
             (["ngay"], "not an object"),
             ({"date": "d", "tong_moi": {}}, "unknown key 'tong_moi'"),
             ({"date": "d", "tong": {"req": 1, "loi": 0, "error_count": 0}}, "both"),
             ({"date": "d", "tong": {"req": 1, "la": 0}}, "unknown key 'la'"),
             ({"date": "d", "tong": []}, "expected dict"),
             ({"date": "d", "theo_model": {"m @ c": {"req": 1, "phien": 2}}}, "unknown key 'phien'"),
             ({"date": "d", "theo_model": {"m @ c": 3}}, "expected dict"),
             ({"date": "d", "top_prompt": {"luc": "x"}}, "expected list"),
             ({"date": "d", "top_prompt": [{"luc": "x", "gio": "y"}]}, "unknown key 'gio'"),
             ({"date": "d", "loi_ket_noi": [{"ten": "c", "name": "c"}]}, "both"),
             ({"date": "d", "loi_ket_noi": ["c"]}, "expected dict"),
             ({"date": "d", "cache_kem": [{"model": "m", "vai": [], "vai_tro": []}]}, "unknown key 'vai_tro'"),
             ({"date": "d", "ket_noi": {"co_watcher": True, "ip": {"1.2.3.4": {"ket_noi": 1}}}}, "legacy_connection.ip"),
             ({"date": "d", "ket_noi": {"co_watcher": False, "ip": {}, "them": 1}}, "unknown key 'them'"),
             ({"date": "d", "vai": {"theo_vai": {"blog/x": {"phien": 1, "sessions": 1}}}}, "both"),
             ({"date": "d", "vai": {"theo_brand": {"blog": {"bai": 1, "so_bai": 1}}}}, "unknown key 'so_bai'"),
             ({"date": "d", "vai": {"tong": 1}}, "unknown key 'tong'"),
             ({"date": "d", "vai": []}, "expected dict"),
             ({"date": "d", "lat_model": []}, "expected dict"),
             ({"date": "d", "loi_doc": ["x"]}, "expected str"))
    for bad, word in cases:
        with tempfile.TemporaryDirectory() as t:
            tmp = Path(t)
            f = _layout(tmp, {"9router_2026-09-01.json": bad})
            before = _bytes(f)
            r = _run(tmp)
            assert r.returncode == 1 and word in r.stderr and "nothing written" in r.stderr, (bad, r.stderr)
            assert _bytes(f) == before and not list(tmp.glob("*.tar.gz")), bad


def test_rerun_is_noop():
    with tempfile.TemporaryDirectory() as t:
        tmp = Path(t)
        f = _layout(tmp, {"9router_2026-09-01.json": {"ngay": "2026-09-01", "ket_noi": {"co_watcher": False, "ip": {}}}})
        assert _run(tmp).returncode == 0
        assert json.loads(f["9router_2026-09-01.json"].read_text(encoding="utf-8")) == {
            "date": "2026-09-01", "legacy_connection": {"has_watcher": False, "ip": {}}}
        after = _bytes(f)
        r = _run(tmp)
        assert r.returncode == 0 and "nothing to do" in r.stdout, r.stdout
        assert _bytes(f) == after and len(list(tmp.glob("*.tar.gz"))) == 1


if __name__ == "__main__":
    from tam import chay_tat_ca
    chay_tat_ca(globals())
