#!/usr/bin/env python3
"""Ada (LOW-246): metrics dump + spec.json + report paths -> English, same text.

Goldens in tests/golden/ada_low246 were generated by running the OLD code (`git show
88f7164:ada_prepare.py` / `:ada_submit.py` in a temp dir) through `run_prepare` /
`use_report` below on the same fixture (globs sorted, time frozen — deterministic on any FS/TZ): `metrics_old.json` (old dump, Vietnamese keys),
`brief.md` (old brief, wd/ROOT paths replaced by <WD>/<ROOT>), `report.txt` and
`report_no_proposals.txt` (old use_report on an old-key spec).

Guards: the new dump holds the same values under the table's new keys (docs/tu_dien_ten/
ada_keys_v2.json); the brief is byte-identical except the spec-template key tokens; the
report is byte-identical for an old-key spec and for the equivalent new-key spec; old spec
keys are normalised in ONE place (ada_submit._legacy_spec, new wins); ada_submit writes
journal/analysis_<date>.md + report.txt, errors name the new keys, a workdir that only has
the pre-LOW-246 `manifest.json` stops with the "not prepared" message instead of crashing;
SOUL names the new spec keys; model_audition's tool schema is English.

Chạy:  venv/bin/python tests/test_ada_keys_english.py
"""
import io
import json
import os
import sys
import tempfile
from contextlib import ExitStack, redirect_stdout
from datetime import datetime as _datetime, timedelta, timezone
from pathlib import Path
from unittest import mock

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "tests"))

GOLDEN = ROOT / "tests" / "golden" / "ada_low246"
JOURNAL_OLD = ROOT / "tests" / "golden" / "router_journal_low239" / "old"
TABLE = json.loads((ROOT / "docs" / "tu_dien_ten" / "ada_keys_v2.json").read_text(encoding="utf-8"))
VN = timezone(timedelta(hours=7))


class _Fixed(_datetime):
    @classmethod
    def now(cls, tz=None):
        return _datetime(2026, 9, 15, 8, 0, tzinfo=tz)


# ------------------------------------------------------------------ fixture
def _candidates(state: Path):
    files = {
        "finn_candidates_2026-09-14.json": {"scan_role": "finn", "items": [
            {"title": "OpenAI ra mắt GPT-6 với chi phí suy luận giảm 40% so với thế hệ trước đó", "score": 92,
             "picked": True, "via": "Google News,rss", "category": "model",
             "assignments": [{"image_role": "hero"}, {"image_role": "body"}]},
            {"title": "Nvidia công bố chip Rubin Ultra cho trung tâm dữ liệu", "score": 88, "picked": False,
             "source_note": "The Verge", "category": "chip"},
            {"title": "Startup AI Việt gọi vốn 12 triệu USD vòng Series A", "score": 72, "picked": True,
             "via": "VnExpress", "category": "funding", "assignments": [{"image_role": "hero"}]},
            {"title": "Tin chưa chấm điểm", "score": None, "picked": False, "category": ""}]},
        "nova_candidates_2026-09-15_t2201.json": {"items": [
            {"title": "Anthropic mở rộng cửa sổ ngữ cảnh lên 2 triệu token", "score": 86, "picked": False,
             "via": "TechCrunch", "category": "model"},
            {"title": "Meta thử nghiệm kính AR mới", "score": 70, "picked": True, "via": "The Verge",
             "category": "device", "assignments": [{"image_role": "cover"}]}]},
        "vera_candidates_2026-09-13.json": {"scan_role": "vera", "items": [
            {"title": "TSMC tăng giá wafer 2nm thêm 8%", "score": 95, "picked": True, "source_note": "Reuters, Bloomberg",
             "category": "chip", "assignments": [{"image_role": "hero"}]}]},
        "qinn_candidates_2026-09-15.json": {"scan_role": "qinn", "items": [
            {"title": "không được gom (qinn)", "score": 99, "picked": False}]},
    }
    for name, d in files.items():
        (state / name).write_text(json.dumps(d, ensure_ascii=False), encoding="utf-8")


def _drafts(drafts: Path):
    (drafts / "d1-gpt6-blog.json").write_text(json.dumps({"status": "published", "brand": "blog"}), encoding="utf-8")
    (drafts / "d1-gpt6-blog.meta.json").write_text(json.dumps({"score": 81}), encoding="utf-8")
    (drafts / "d1-gpt6-blog.img.json").write_text("{}", encoding="utf-8")
    (drafts / "d2-rubin-dcgr.json").write_text(json.dumps({"status": "pending", "brand": "dcgr"}), encoding="utf-8")
    (drafts / "d3-meta-ar.json").write_text(json.dumps({"status": "rejected", "brand": "blog"}), encoding="utf-8")


JOBS = [
    {"id": "t1", "assignee": "miles", "status": "done", "title": "Viết bài GPT-6", "error": None,
     "started_at": 1000, "completed_at": 1600},
    {"id": "t2", "assignee": "miles", "status": "done", "title": "Viết bài TSMC", "error": None,
     "started_at": 2000, "completed_at": 2300},
    {"id": "t3", "assignee": "dre", "status": "blocked", "title": "Ảnh cho bài chip Rubin", "error": "thiếu ảnh thật",
     "started_at": 3000, "completed_at": None},
    {"id": "t4", "assignee": "ada", "status": "failed", "title": "Phân tích tuần", "error": "timeout " + "x" * 200,
     "started_at": None, "completed_at": None},
    {"id": "t5", "assignee": "finn", "status": "done", "title": "Quét tin sáng", "error": "cảnh báo nhẹ",
     "started_at": 10, "completed_at": 70},
]

SESSIONS = {
    "miles": {"sessions": 3, "tool": 41, "input": 1234567, "api": 52,
              "top": [("Viết bài GPT-6", 20, 600000), ("Viết bài TSMC", 11, 300000)]},
    "dre": {"sessions": 2, "tool": 12, "input": 45678, "api": 14, "top": [("Ảnh cho bài chip Rubin", 12, 45678)]},
    "ada": {"sessions": 0, "tool": 0, "input": 0, "api": 0, "top": []},
    "qinn": None,
}


def _journals() -> dict:
    # LOW-251: ban da migrate san (script migrate_9router_journal da go sau khi chay tren may chu)
    out = {}
    for p in sorted((JOURNAL_OLD.parent / "migrated").glob("9router_*.json")):
        d = json.loads(p.read_text(encoding="utf-8"))
        out[d["date"]] = d
    return out


def run_prepare(ap, tmp: Path, ngay: int = 2):
    """Run `ap.main()` (old or new ada_prepare) on the fixture. -> (dump, brief, wd)."""
    import env_load
    import hermes_adapter
    import monitor_9router
    state, drafts, home = tmp / "state", tmp / "drafts", tmp / "hermes"
    for d in (state, drafts, home):
        d.mkdir(parents=True, exist_ok=True)
    _candidates(state)
    _drafts(drafts)
    journals = _journals()
    profiles = [home / "profiles" / n / "state.db" for n in SESSIONS]
    real_glob = Path.glob
    with ExitStack() as st:
        # readdir order differs by filesystem (APFS vs ext4 on CI): ada_prepare builds
        # `draft.by_status` (and the brief/report line) in glob order, so the fixture sorts it.
        st.enter_context(mock.patch.object(Path, "glob", lambda self, pat, *a, **k:
                                           iter(sorted(real_glob(self, pat, *a, **k)))))
        st.enter_context(mock.patch.object(env_load, "state_dir", lambda: state))
        st.enter_context(mock.patch.object(ap, "DRAFTS", drafts))
        st.enter_context(mock.patch.object(ap, "HERMES", home))
        st.enter_context(mock.patch.object(ap, "datetime", _Fixed))
        st.enter_context(mock.patch.object(hermes_adapter, "job", lambda tu_ts=None, **k: [dict(j) for j in JOBS]))
        st.enter_context(mock.patch.object(hermes_adapter, "state_db_each_profile", lambda h: list(profiles)))
        st.enter_context(mock.patch.object(hermes_adapter, "summary_session",
                                           lambda p, moc: SESSIONS[p.parent.name]))
        st.enter_context(mock.patch.object(monitor_9router, "download",
                                           lambda d, lam_moi=False: json.loads(json.dumps(journals[d]))
                                           if d in journals else None))
        st.enter_context(mock.patch.dict(os.environ, {"CT_BRAND": "blog"}))
        st.enter_context(mock.patch.object(sys, "argv", ["ada_prepare.py", "--ngay", str(ngay), "--im"]))
        assert ap.main() == 0
        wd = ap.workdir()
    (dump_file,) = [p for p in wd.glob("*.json")]
    dump = json.loads(dump_file.read_text(encoding="utf-8"))
    brief = (wd / "brief.md").read_text(encoding="utf-8")
    brief = brief.replace(str(wd), "<WD>").replace(str(ap.ROOT), "<ROOT>")
    return dump, brief, wd, dump_file.name


OLD_SPEC = {
    "nhan_xet": ["Tin điểm ≥90 được chọn 2/2, tin 80–89 chọn 0/2 — bài Nvidia 88 bị bỏ.",
                 "miles đốt 1,234,567 input token trong 3 phiên."],
    "de_xuat_rubric": [{"thay_doi": "Giảm trọng số độ mới cho tin chip", "bang_chung": "Nvidia Rubin 88 điểm bị bỏ"},
                       {"thay_doi": "Tăng ngưỡng tin gọi vốn", "bang_chung": "Startup AI Việt 72 điểm được chọn"}],
    "token": "miles nặng nhất với 1,234,567 input.",
    "router": "Ngày 09-15 đốt $0.223, có 1 fallback.",
    "ket_luan": "Rubric chấm tin chip thấp hơn thực tế.",
}
NEW_SPEC = {
    "observations": OLD_SPEC["nhan_xet"],
    "rubric_proposals": [{"change": x["thay_doi"], "evidence": x["bang_chung"]} for x in OLD_SPEC["de_xuat_rubric"]],
    "token": OLD_SPEC["token"],
    "router": OLD_SPEC["router"],
    "conclusion": OLD_SPEC["ket_luan"],
}
OLD_SPEC_EMPTY = dict(OLD_SPEC, de_xuat_rubric=[])
NEW_SPEC_EMPTY = dict(NEW_SPEC, rubric_proposals=[])

# Spec-template tokens in the brief: the only text allowed to change (old -> new).
BRIEF_TOKENS = [('"nhan_xet"', '"observations"'), ('"de_xuat_rubric"', '"rubric_proposals"'),
                ('"thay_doi"', '"change"'), ('"bang_chung"', '"evidence"'), ('"ket_luan"', '"conclusion"'),
                ("ghi de_xuat_rubric: []", "ghi rubric_proposals: []")]
SPEC_HEADING = "## Viết nhận xét vào:"


# ------------------------------------------------------------------ helpers
def _pairs(old, new, path="", out=None):
    """Walk old and new dumps in parallel: same values under the same or renamed keys.
    Keys present in both pair BY NAME (data keys: roles, statuses, models); only the
    leftover (renamed) keys pair by position, which the code's dict literals fix.
    -> {(path of the parent, old key, new key)} for every renamed key."""
    out = set() if out is None else out
    if isinstance(old, dict):
        assert isinstance(new, dict) and len(old) == len(new), (path, list(old), new)
        only_old = [k for k in old if k not in new]
        only_new = [k for k in new if k not in old]
        pairs = [(k, k) for k in old if k in new] + list(zip(only_old, only_new))
        for ko, kn in pairs:
            if ko != kn:
                out.add((path, ko, kn))
            _pairs(old[ko], new[kn], f"{path}.{kn}" if path else kn, out)
    elif isinstance(old, list):
        assert isinstance(new, list) and len(old) == len(new), (path, old, new)
        for vo, vn in zip(old, new):
            _pairs(vo, vn, path + "[]", out)
    else:
        assert old == new, (path, old, new)
    return out


def _generic(path: str) -> str:
    """Dump path -> table section name (profile/model/brand/date keys become `*`)."""
    parts = path.split(".") if path else []
    out = []
    for p in parts:
        prev = out[-1] if out else ""
        if prev in ("by_role", "cost_by_role", "brand", "by_score_tier", "by_source", "by_category",
                    "router_cost_by_model", "by_status", "avg_seconds"):
            out.append("*")
        elif p in ("high_score_dropped[]", "low_score_picked[]"):
            out.append("items[]")
        else:
            out.append(p)
    return ".".join(["ada_metrics"] + out)


def _run_submit(asub, wd: Path, state: Path, spec: dict, *argv):
    (wd / "spec.json").write_text(json.dumps(spec, ensure_ascii=False), encoding="utf-8")
    import ada_prepare
    import env_load
    buf = io.StringIO()
    with mock.patch.object(env_load, "state_dir", lambda: state), \
            mock.patch.object(ada_prepare, "datetime", _Fixed), \
            mock.patch.object(asub, "datetime", _Fixed), \
            mock.patch.object(sys, "argv", ["ada_submit.py", *argv]), redirect_stdout(buf):
        try:
            rc = asub.main()
        except SystemExit as e:
            rc = e.code
    return rc, buf.getvalue()


# ------------------------------------------------------------------ tests
def test_metrics_dump_same_values_under_table_keys():
    import ada_prepare
    import state_paths
    old = json.loads((GOLDEN / "metrics_old.json").read_text(encoding="utf-8"))
    with tempfile.TemporaryDirectory() as t:
        new, _, wd, name = run_prepare(ada_prepare, Path(t))
    assert name == state_paths.ADA_METRICS_FILE == TABLE["files"]["manifest.json"], name
    renamed = _pairs(old, new)
    assert renamed, "golden dump must differ in keys"
    missing = sorted((p, o, n) for p, o, n in renamed if TABLE.get(_generic(p), {}).get(o) != n)
    assert not missing, f"renamed key not in ada_keys_v2.json (section, old, new): {missing}"
    root = {k: v for k, v in TABLE["ada_metrics"].items() if not k.startswith("_")}
    assert list(new) == ["days", "brand", "candidates", "draft", "kanban", "token"] and \
        {("", o, n) for o, n in root.items()} <= renamed, list(new)
    # every table row of the dump is exercised by the fixture (a table row nobody writes is a typo)
    rows = {(sec, o, n) for sec, m in TABLE.items() if sec.startswith("ada_metrics")
            for o, n in m.items() if not o.startswith("_") and sec != "ada_metrics.token.router_journal_in_memory"}
    seen = {(_generic(p), o, n) for p, o, n in renamed}
    assert rows == seen, (sorted(rows - seen), sorted(seen - rows))


def test_brief_identical_except_spec_template_tokens():
    import ada_prepare
    golden = (GOLDEN / "brief.md").read_text(encoding="utf-8")
    with tempfile.TemporaryDirectory() as t:
        _, brief, _, _ = run_prepare(ada_prepare, Path(t))
    head, tail = golden.split(SPEC_HEADING)
    for o, n in BRIEF_TOKENS:
        assert o in tail, o
        tail = tail.replace(o, n)
    assert brief == head + SPEC_HEADING + tail, brief
    assert all(o not in brief for o, _ in BRIEF_TOKENS)
    # the JSON template is the table's spec keys, in order
    spec = json.loads(brief.split(SPEC_HEADING)[1].split("\n", 1)[1].rsplit("\nKhông có gì", 1)[0])
    assert list(spec) == ["observations", "rubric_proposals", "token", "router", "conclusion"], spec
    assert list(spec["rubric_proposals"][0]) == ["change", "evidence"]


def test_report_identical_for_old_and_new_spec_keys():
    import ada_prepare
    import ada_submit as asub
    with tempfile.TemporaryDirectory() as t:
        m, _, _, _ = run_prepare(ada_prepare, Path(t))
    for old, new, gold in ((OLD_SPEC, NEW_SPEC, "report.txt"), (OLD_SPEC_EMPTY, NEW_SPEC_EMPTY, "report_no_proposals.txt")):
        want = (GOLDEN / gold).read_text(encoding="utf-8")
        assert asub.use_report(m, asub._legacy_spec(old)) == want, gold
        assert asub.use_report(m, asub._legacy_spec(new)) == want, gold
        assert asub.use_report(m, new) == want, gold
        assert asub._legacy_spec(old) == new


def test_legacy_spec_new_wins_and_keeps_unknown():
    import ada_submit as asub
    mixed = {"nhan_xet": ["cũ"], "observations": ["mới"], "ket_luan": "cũ", "note": 1,
             "de_xuat_rubric": [{"thay_doi": "a", "bang_chung": "b"}],
             "rubric_proposals": [{"thay_doi": "x", "change": "y", "bang_chung": "z"}, "not a dict"]}
    got = asub._legacy_spec(mixed)
    assert got == {"observations": ["mới"], "conclusion": "cũ", "note": 1,
                   "rubric_proposals": [{"change": "y", "evidence": "z"}, "not a dict"]}, got
    assert asub._legacy_spec([1]) == [1]
    assert mixed["nhan_xet"] == ["cũ"], "input must not be mutated"
    for o, n in TABLE["ada_spec"].items():
        if not o.startswith("_"):
            assert asub._legacy_spec({o: "v"}) == {n: "v"}, o


def test_submit_writes_new_paths_for_old_and_new_spec():
    import ada_prepare
    import ada_submit as asub
    import state_paths
    want = (GOLDEN / "report.txt").read_text(encoding="utf-8")
    for spec in (OLD_SPEC, NEW_SPEC):
        with tempfile.TemporaryDirectory() as t:
            _, _, wd, _ = run_prepare(ada_prepare, Path(t))
            state = Path(t) / "state"
            rc, out = _run_submit(asub, wd, state, spec, "--khong-gui")
            assert rc == 0, out
            md = state / state_paths.JOURNAL_DIR / f"{state_paths.ANALYSIS_REPORT_PREFIX}2026-09-15.md"
            assert md.name == TABLE["files"]["phan_tich_{date}.md"].replace("{date}", "2026-09-15")
            assert md.read_text(encoding="utf-8") == want
            assert (wd / state_paths.ADA_REPORT_FILE).read_text(encoding="utf-8") == want
            assert state_paths.ADA_REPORT_FILE == TABLE["files"]["bao_cao.txt"]
            assert not list(state.rglob("phan_tich_*")) and not list(state.rglob("bao_cao.txt"))


def test_submit_errors_name_new_keys():
    import ada_prepare
    import ada_submit as asub
    for spec in ({"de_xuat_rubric": [{"thay_doi": "Đổi trọng số", "bang_chung": ""}], "ket_luan": "Khong dau gi ca het"},
                 {"rubric_proposals": [{"change": "Đổi trọng số", "evidence": ""}], "conclusion": "Khong dau gi ca het"}):
        with tempfile.TemporaryDirectory() as t:
            _, _, wd, _ = run_prepare(ada_prepare, Path(t))
            rc, out = _run_submit(asub, wd, Path(t) / "state", spec, "--khong-gui")
        assert rc == 1, out
        assert "[LOI] thiếu observations" in out, out
        assert '[LOI] rubric_proposals thiếu evidence: "Đổi trọng số"' in out, out
        assert "[LOI] conclusion: tiếng Việt mất dấu" in out, out
        for o in ("nhan_xet", "de_xuat_rubric", "bang_chung", "thay_doi", "ket_luan"):
            assert o not in out, (o, out)


def test_submit_old_workdir_without_metrics_stops_cleanly():
    import ada_prepare
    import ada_submit as asub
    import state_paths
    with tempfile.TemporaryDirectory() as t:
        _, _, wd, _ = run_prepare(ada_prepare, Path(t))
        (wd / state_paths.ADA_METRICS_FILE).rename(wd / "manifest.json")     # pre-LOW-246 workdir
        rc, out = _run_submit(asub, wd, Path(t) / "state", NEW_SPEC, "--khong-gui")
    assert rc == "Chưa chuẩn bị. Chạy trước: venv/bin/python ada_prepare.py", (rc, out)


def test_soul_and_sources_name_only_new_spec_keys():
    soul = (ROOT / "hermes" / "profiles" / "shared" / "ada.SOUL.md").read_text(encoding="utf-8")
    assert "(observations, rubric_proposals, token, router, conclusion)" in soul, soul
    old = [o for sec in ("ada_spec", "ada_spec.rubric_proposals[]") for o in TABLE[sec] if not o.startswith("_")]
    for f in ("ada_prepare.py", "hermes/profiles/shared/ada.SOUL.md"):
        text = (ROOT / f).read_text(encoding="utf-8")
        assert not [o for o in old if o in text], f
    sub = (ROOT / "ada_submit.py").read_text(encoding="utf-8").splitlines()
    outside = [ln for ln in sub if not ln.startswith(("LEGACY_SPEC_KEYS = ", "LEGACY_PROPOSAL_KEYS = "))]
    assert len(outside) == len(sub) - 2 and not [o for o in old if o in "\n".join(outside)], \
        "old spec keys only in the LEGACY_* alias maps used by _legacy_spec"


def test_model_audition_tool_schema_english():
    import model_audition as ma
    fn = ma.TOOLS[0]["function"]
    t = TABLE["model_audition"]
    assert fn["name"] == t["tool_name"]["luu_caption"] == "save_caption", fn
    assert list(fn["parameters"]["properties"]) == ["caption", t["tool_parameters"]["chu_de"]], fn
    assert fn["parameters"]["required"] == ["caption", "topic"], fn
    src = (ROOT / "model_audition.py").read_text(encoding="utf-8")
    assert "luu_caption" not in src and "chu_de" not in src


if __name__ == "__main__":
    from tam import chay_tat_ca
    chay_tat_ca(globals())
